"""
=============================================================================
Module: research.models
Description: Research ORM model – represents an AI-generated deep research
             report with its lifecycle status and content.
             研究报告ORM模型 - 表示AI生成的深度研究报告及其生命周期状态和内容。
Created: 2026-04-06
Author: PolaZhenjing Team
Dependencies: sqlalchemy, app.database, app.common.models
=============================================================================
"""

import enum
import uuid

from sqlalchemy import Enum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.common.models import TimestampMixin
from app.database import Base


class ResearchStatus(str, enum.Enum):
    """Lifecycle status of a research report."""
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class Research(TimestampMixin, Base):
    """
    A deep research report generated by the AI pipeline.

    Business rules:
        - Every research belongs to one author (User).
        - status starts as PENDING, transitions through GENERATING to
          COMPLETED or FAILED.
        - html_content stores the final rendered HTML report.
    """

    __tablename__ = "researches"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False, default="")
    query: Mapped[str] = mapped_column(Text, nullable=False)
    outline: Mapped[str | None] = mapped_column(Text, nullable=True)
    content: Mapped[str | None] = mapped_column(Text, nullable=True)
    html_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[ResearchStatus] = mapped_column(
        Enum(ResearchStatus), default=ResearchStatus.PENDING, nullable=False
    )
    source_urls: Mapped[str | None] = mapped_column(Text, nullable=True)
    metadata_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Foreign key to User
    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Relationships
    author: Mapped["User"] = relationship(lazy="selectin")  # noqa: F821

    def __repr__(self) -> str:
        return f"<Research {self.title[:40]}>"
